Import('env', 'ALTA_LIBS')
env = env.Clone()

env.Prepend(LIBS = ['core'])
env.AppendUnique(LIBS = ALTA_LIBS)

sources = ['data2stats.cpp']
program = env.Program('#build/softs/data2stats', sources)
env.Install(env['INSTALL_PREFIX'] + '/bin', program)
