Import('env', 'ALTA_LIBS')
env = env.Clone()

env.Prepend(LIBS = ['core'])
env.AppendUnique(LIBS = ALTA_LIBS)

# Soft Sources
sources = ['data2stats.cpp']

env.Program('../../build/data2stats', sources)
