Import('env', 'ALTA_LIBS')

sources = ['fit2stat.cpp']
program = env.Program('#build/softs/fit2stat', sources,
                      LIBS = ['core'] + ALTA_LIBS)
env.Install(env['INSTALL_PREFIX'] + '/bin', program)
