# Plug-ins.

plugins = [ 'data_interpolant',
            'data_io',

            # Building nonlinear fitters.
            'nonlinear_fitter_ceres',
            'nonlinear_fitter_nlopt',
            'nonlinear_fitter_ipopt',
            'nonlinear_fitter_eigen',

            # Building nonlinear functions.
            'nonlinear_function_diffuse',
            'nonlinear_function_beckmann',
            'nonlinear_function_abc',
            'nonlinear_function_blinn',
            'nonlinear_function_isotropic_lafortune',
            'nonlinear_function_sgd',
            'nonlinear_function_ward',

            # Building nonlinear masking functions.
            'nonlinear_shadowing_smith',
            'nonlinear_shadowing_walter_smith',

            # Building nonlinear Fresnel functions.
            'nonlinear_fresnel_schlick',
            'nonlinear_fresnel_normalized_schlick',

            # Building rational fitters.
            'rational_fitter_eigen',
            'rational_fitter_leastsquare',
            'rational_fitter_quadprog',
            'rational_fitter_parallel',
            'rational_fitter_matlab',

            # Building rational functions.
            'rational_function_legendre',
            'rational_function_chebychev',
            'rational_function_cosine',

            # Building retro functions.
            'nonlinear_function_retroblinn',
            'nonlinear_function_retroyoo',
            'nonlinear_function_retrobeckmann',
            'nonlinear_fresnel_retroschlick' ]

def build_plugin(directory):
  return SConscript(directory + '/SConscript')

# Build them all!
map(build_plugin, plugins)
