# Building datas
SConscript('data_merl/SConscript')
SConscript('data_brdf_slice/SConscript')
SConscript('data_interpolant/SConscript')

# Building fitters
SConscript('nonlinear_fitter_ceres/SConscript')
SConscript('nonlinear_fitter_nlopt/SConscript')
SConscript('nonlinear_fitter_eigen/SConscript')
SConscript('rational_fitter_eigen/SConscript')
SConscript('rational_fitter_quadprog/SConscript')

# Building functions
SConscript('nonlinear_function_diffuse/SConscript')
SConscript('nonlinear_function_beckmann/SConscript')
SConscript('nonlinear_function_retrobeckmann/SConscript')
SConscript('nonlinear_function_abc/SConscript')
SConscript('nonlinear_function_blinn/SConscript')
SConscript('nonlinear_function_retroblinn/SConscript')
SConscript('nonlinear_function_retroyoo/SConscript')
SConscript('rational_function_legendre/SConscript')
SConscript('rational_function_chebychev/SConscript')
SConscript('nonlinear_function_isotropic_lafortune/SConscript')
