# # Building data plugins
#SConscript('data_merl/SConscript')
SConscript('data_brdf_slice/SConscript')
SConscript('data_interpolant/SConscript')
SConscript('data_io/SConscript')

# # Building nonlinear fitters
SConscript('nonlinear_fitter_ceres/SConscript')
SConscript('nonlinear_fitter_nlopt/SConscript')
SConscript('nonlinear_fitter_ipopt/SConscript')
SConscript('nonlinear_fitter_eigen/SConscript')

# Building nonlinear functions
SConscript('nonlinear_function_diffuse/SConscript')
SConscript('nonlinear_function_beckmann/SConscript')
SConscript('nonlinear_function_abc/SConscript')
SConscript('nonlinear_function_blinn/SConscript')
SConscript('nonlinear_function_isotropic_lafortune/SConscript')
SConscript('nonlinear_function_sgd/SConscript')
SConscript('nonlinear_function_ward/SConscript')


# Building nonlinear masking functions
SConscript('nonlinear_shadowing_smith/SConscript')
SConscript('nonlinear_shadowing_walter_smith/SConscript')


# Building nonlinear Fresnel functions
SConscript('nonlinear_fresnel_schlick/SConscript')
SConscript('nonlinear_fresnel_normalized_schlick/SConscript')

# # Building rational fitters
SConscript('rational_fitter_eigen/SConscript')
SConscript('rational_fitter_leastsquare/SConscript')
SConscript('rational_fitter_quadprog/SConscript')
SConscript('rational_fitter_parallel/SConscript')
SConscript('rational_fitter_matlab/SConscript')
# This SConscript does not exist on the master branch
#SConscript('rational_fitters/SConscript')


# # Building rational functions
SConscript('rational_function_legendre/SConscript')
SConscript('rational_function_chebychev/SConscript')
SConscript('rational_function_cosine/SConscript')


# Building retro functions
SConscript('nonlinear_function_retroblinn/SConscript')
SConscript('nonlinear_function_retroyoo/SConscript')
SConscript('nonlinear_function_retrobeckmann/SConscript')
SConscript('nonlinear_fresnel_retroschlick/SConscript')
