SConscript('data2brdf/SConscript')
SConscript('data2data/SConscript')
SConscript('data2moments/SConscript')

SConscript('brdf2brdf/SConscript')
SConscript('brdf2data/SConscript')
SConscript('brdf2gnuplot/SConscript')

SConscript('fit2stat/SConscript')
SConscript('data2stats/SConscript')