Import('env')
env = env.Clone()

# Special linking flags, defined in the OS dependant configuration file
env.AppendUnique(LIBS = env['SOFT_LIB'])

# Soft Sources
sources = ['main.cpp']

env.Program('../../build/brdf2brdf', sources)
