import os

env = Environment()
env.Append(CPPPATH = '../../external/build/include')

# Library sources
sources = ['common.cpp', 
           'function.cpp', 
           'params.cpp', 
           'plugins_manager.cpp', 
           'rational_function.cpp', 
           'vertical_segment.cpp']

libs = []
if(os.name == 'posix'):
	libs = ['rt', 'dl']
#end

env.StaticLibrary('../build/core', sources, LIBS=libs)
