import os
import sys

Import('env')
env = env.Clone()

# Library sources
sources = ['common.cpp', 
           'function.cpp', 
           'params.cpp', 
           'plugins_manager.cpp', 
           'rational_function.cpp', 
           'vertical_segment.cpp']

if(os.name == 'posix'):
	env.AppendUnique(LIBS = ['rt', 'dl'])
#end

## Known compilation issue. If the core is not compiled with -fvisibility-hidden
## on OSX, the shared libraries and the softwares cannot share vtables. This
## impact the use of dynamic_cast in shared libraries.
##
if sys.platform == 'darwin':
	env.AppendUnique(CCFLAGS = '-fvisibility=hidden')
#end

env.StaticLibrary('../build/core', sources)