core    = SConscript('core/SConscript')
plugins = SConscript('plugins/SConscript')
softs   = SConscript('softs/SConscript')

python  = SConscript('python/SConscript')
#Requires(plugins, core)
#Requires(softs, core)
