Import('env')

sources = ['function.cpp']
env.SharedLibrary('#build/plugins/nonlinear_function_abc', sources,
                  LIBS = env['PLUGIN_LIB'])
Return('sources')               # always built
