env = Environment()
env.Append(CPPPATH = ['../../../external/quadprog++', '../../../external/build/include', '../../'])
env.Append(LIBPATH = ['../../../external/build/lib'])

sources = ['rational_fitter.cpp']
libs = ['-lcore', '-lquadprog++']
targets = env.SharedLibrary('#build/plugins/rational_fitter_quadprog',
                            sources, LIBS=libs)

Return('targets')
