env = Environment()
env.Append(CPPPATH = ['../../../external/build/include', '../../'])
env.Append(LIBPATH = ['../../build'])

sources = ['data.cpp']
libs = ['-lcore']
env.SharedLibrary('../../build/data_merl', sources, LIBS=libs)
