Import('env')

sources = ['rational_fitter.cpp']
targets = env.SharedLibrary('#build/plugins/rational_fitter_leastsquare',
                            sources, LIBS = env['PLUGIN_LIB'])
Return('targets')
