Import('env')

sources = ['rational_function.cpp']
env.SharedLibrary('../../build/rational_function_legendre', sources,
                  LIBS = env['PLUGIN_LIB'])
Return('sources')               # always built
