Import('env')

sources = ['rational_fitter.cpp']
env.SharedLibrary('#build/plugins/rational_fitter_eigen', sources,
                  LIBS = env['PLUGIN_LIB'])
Return('sources')               # always built
