Import('env')

sources = ['function.cpp']
targets = env.SharedLibrary('#build/plugins/nonlinear_shadowing_walter_smith',
                            sources, LIBS = env['PLUGIN_LIB'])
Return('targets')
