env = Environment()
env.Append(CPPPATH = ['../../../external/quadprog++', '../../../external/build/include', '../../'])
env.Append(LIBPATH = ['../../../external/build/lib', '../../build'])

sources = ['rational_fitter.cpp']
libs = ['core', 'quadprog++']
env.SharedLibrary('../../build/rational_fitter_quadprog', sources, LIBS=libs)
