Import('env')
env = env.Clone()

env.AppendUnique(CPPPATH = env['QUADPROG_INC'])
env.AppendUnique(LIBPATH = env['QUADPROG_DIR'])
env.AppendUnique(LIBS    = env['QUADPROG_LIB'])
env.AppendUnique(LIBS    = env['PLUGIN_LIB'])

build_lib = False

conf = Configure(env)

if conf.CheckLib(env['QUADPROG_LIB'], language='c++'):

	build_lib = True
	
#end
conf.Finish()

if build_lib:
	sources = ['rational_fitter.cpp']
	env.SharedLibrary('../../build/rational_fitter_quadprog', sources)
#end
