Import('env', 'CheckPKG')
env = env.Clone()

env.AppendUnique(LIBS    = env['PLUGIN_LIB'])
env.AppendUnique(LIBPATH = env['OPENEXR_DIR'])
env.AppendUnique(CPPPATH = env['OPENEXR_INC'])

build_lib = False
conf = Configure(env, custom_tests = { 'CheckPKG' : CheckPKG })

# Check we have the necessary dependency.
if conf.CheckPKG('OpenEXR'):
        env.ParseConfig('pkg-config --cflags --libs OpenEXR')
        if conf.CheckLibWithHeader('IlmImf', 'ImfRgbaFile.h', 'c++'):
                build_lib = True

env = conf.Finish()

if build_lib:
	sources = ['data.cpp']
	env.SharedLibrary('../../build/data_brdf_slice', sources)
#end
