Import('env', 'CheckPKG')
env = env.Clone()

env.AppendUnique(LIBS    = env['PLUGIN_LIB'])
env.AppendUnique(LIBPATH = env['OPENEXR_DIR'])
env.AppendUnique(CPPPATH = env['OPENEXR_INC'])

build_lib = False
conf = Configure(env, custom_tests = { 'CheckPKG' : CheckPKG })

# Check we have the necessary dependency.
if conf.CheckPKG('IlmBase'):
        env.ParseConfig('pkg-config --cflags --libs IlmBase')
        if conf.CheckLibWithHeader('Half', 'ImfRgbaFile.h', 'c++'):
                env.AppendUnique(LIBS = ['Half'])
                build_lib = True

env = conf.Finish()

if build_lib:
	sources = ['data.cpp']
	env.SharedLibrary('../../build/data_brdf_slice', sources)
#end
