env = Environment()
env.Append(CPPPATH = ['../../../external/build/include', '../../', '/usr/include/OpenEXR/'])
env.Append(LIBPATH = ['../../build'])

sources = ['data.cpp']
libs = ['-lcore', '-lIlmImf', '-lIlmThread']
env.SharedLibrary('../../build/data_brdf_slice', sources, LIBS=libs)
