Import('env', 'openexr_available')
env = env.Clone()

# Special linking flags, defined in the OS dependant configuration file
env.AppendUnique(LIBS = env['PLUGIN_LIB'])

env.SharedLibrary('../../build/data_merl', ['merl.cpp'])
env.SharedLibrary('../../build/data_astm', ['astm.cpp'])

build_lib = openexr_available(env)
if build_lib:
  env.SharedLibrary('../../build/data_utia', ['utia.cpp'])
  env.SharedLibrary('../../build/data_brdf_slice', ['slice.cpp'])

Return('build_lib')
