import sys

env = Environment()
env.Append(CPPPATH = ['../../', '../../../external/build/include'])

# Soft Sources
sources = ['main.cpp']

libs = ['core']
if sys.platform == 'linux2':
	libs.append(['rt', 'dl'])
elif sys.platform == 'darwin':
	libs.append(['dl'])
#end

env.Program('../../build/brdf2gnuplot', sources, LIBS=libs, LIBPATH=['../../build'])
