Import('env')

sources = ['function.cpp']
env.SharedLibrary('../../build/nonlinear_function_retrobeckmann', sources,
                  LIBS = env['PLUGIN_LIB'])
Return('sources')               # always built
