import sys

Import('env')
env = env.Clone()

# Soft Sources
sources = ['main.cpp']

libs = ['core']
if sys.platform == 'linux2':
	libs.append(['rt', 'dl'])
elif sys.platform == 'darwin':
	libs.append(['dl'])
#end

env.Program('../../build/data2brdf', sources, LIBS=libs, LIBPATH=['../../build'])
