Import('env', 'ALTA_LIBS')

sources = ['main.cpp']
program = env.Program('#build/softs/brdf2moments', sources,
                      LIBS = ['core'] + ALTA_LIBS)
env.Install(env['INSTALL_PREFIX'] + '/bin', program)
