Import('env')
env = env.Clone()

env.AppendUnique(LIBS = env['PLUGIN_LIB'])

conf = Configure(env)

if conf.CheckCXXHeader('unsupported/Eigen/LevenbergMarquardt'):

	sources = ['fitter.cpp']
	env.SharedLibrary('../../build/nonlinear_fitter_eigen', sources)

#end

env = conf.Finish()
