env = Environment()
env.Append(CPPPATH = ['../../../external/build/include', '../../../external/build/include/Eigen', '../../'])
env.Append(LIBPATH = ['../../build'])

sources = ['fitter.cpp']
libs = ['core']
env.SharedLibrary('../../build/nonlinear_fitter_eigen', sources, LIBS=libs)
