env = Environment()
env.Append(CPPPATH = ['../../../external/build/include', '../../'])
env.Append(LIBPATH = ['../../../external/build/lib', '../../build'])

sources = ['function.cpp']
libs = ['core']
env.SharedLibrary('../../build/nonlinear_function_diffuse', sources, LIBS=libs)
