Import('env', 'ALTA_LIBS')
env = env.Clone()

if env['OPENMP_LINKFLAGS']:
  env.AppendUnique(CCFLAGS = env['OPENMP_CFLAGS'])
  env.AppendUnique(LINKFLAGS = env['OPENMP_LINKFLAGS'])

env.Prepend(LIBS = ['core'])
env.AppendUnique(LIBS = ALTA_LIBS)


sources = ['main.cpp']
env.Program('#build/softs/data2data', sources)
