Import('env')

sources = ['rational_function.cpp']
targets = env.SharedLibrary('#build/plugins/rational_function_chebychev',
                            sources, LIBS = env['PLUGIN_LIB'])
Return('targets')
