Import('env')

sources = ['rational_function.cpp']
env.SharedLibrary('#build/plugins/rational_function_chebychev', sources,
                  LIBS = env['PLUGIN_LIB'])
Return('sources')               # always built
