Import('env')
env = env.Clone()

conf = Configure(env)
if conf.CheckLib(env['FLANN_LIB']):

	env.AppendUnique(LIBS    = env['PLUGIN_LIB'])
	env.AppendUnique(LIBS    = env['FLANN_LIB'])
	env.AppendUnique(LIBPATH = env['FLANN_DIR'])
	env.AppendUnique(CPPPATH = env['FLANN_INC'])

	sources = ['data.cpp']
	env.SharedLibrary('../../build/data_interpolant', sources)

#end
env = conf.Finish()
