Import('env')
env = env.Clone()

conf = Configure(env)
build_lib = conf.CheckLibWithHeader(env['FLANN_LIB'], 'flann/flann.hpp', 'CXX')
env = conf.Finish()

if build_lib:
  env.AppendUnique(LIBS    = env['PLUGIN_LIB'])
  env.AppendUnique(LIBS    = env['FLANN_LIB'])
  env.AppendUnique(LIBPATH = env['FLANN_DIR'])
  env.AppendUnique(CPPPATH = env['FLANN_INC'])

  sources = ['data.cpp']
  env.SharedLibrary('../../build/data_interpolant', sources)
