env = Environment()
env.Append(CPPPATH = ['../../../external/build/include', '../../'])
env.Append(LIBPATH = ['../../build'])

sources = ['data.cpp']
libs = ['flann', 'core']
env.SharedLibrary('../../build/data_interpolant', sources, LIBS=libs)
