env = Environment()
env.Append(CPPPATH = ['../../../external/build/include', '../../'])
env.Append(LIBPATH = ['../../../external/build/lib', '../../build'])

sources = ['fitter.cpp']
libs = ['-lnlopt', '-lcore']
env.SharedLibrary('../../build/nonlinear_fitter_nlopt', sources, LIBS=libs)
