Import('env')
env = env.Clone()

env.AppendUnique(LIBS    = env['PLUGIN_LIB'])
env.AppendUnique(LIBS    = env['NLOPT_LIB'])
env.AppendUnique(LIBPATH = env['NLOPT_DIR'])
env.AppendUnique(CPPPATH = env['NLOPT_INC'])

build_lib = False

conf = Configure(env)

if conf.CheckLib(env['NLOPT_LIB']):

	if conf.CheckLib(env['NLOPT_OPT_LIB']):
		env.AppendUnique(LIBS = env['NLOPT_OPT_LIB'])
	#end

	build_lib = True

#end
env = conf.Finish()

if build_lib:
	sources = ['fitter.cpp']
	env.SharedLibrary('../../build/nonlinear_fitter_nlopt', sources)
#end