Import('env')
env = env.Clone()

env.AppendUnique(CPPPATH = ['../../../external/build/include', '../../'])
env.AppendUnique(LIBPATH = ['../../../external/build/lib', '../../build'])

sources = ['fitter.cpp']
libs = ['ceres', 'glog', 'core', 'lapack', 'blas']

conf = Configure(env)
# Main dependencies of the CERES plugins: CEREs and GLOG
# GOMP, LAPACK and BLAS are also tested and added if found. If not
# CERES might not have been compiled with those dependencies.
if conf.CheckLib('ceres') and conf.CheckLib('glog'):

	if conf.CheckLib('gomp'):
		libs.append('gomp')
	#end

	if conf.CheckLib('lapack'):
		libs.append('lapack')
	#end
	
	if conf.CheckLib('blas'):
		libs.append('blas')
	#end

	if conf.CheckLib('cxsparse'):
		libs.append('cxsparse')
	#end

	if conf.CheckLib('cholmod'):
		libs.append('cholmod')
	#end

	if conf.CheckLib('amd'):
		libs.append('amd')
	#end

	if conf.CheckLib('camd'):
		libs.append('camd')
	#end

	if conf.CheckLib('colamd'):
		libs.append('colamd')
	#end

	if conf.CheckLib('ccolamd'):
		libs.append('ccolamd')
	#end

	if conf.CheckLib('ldl'):
		libs.append('ldl')
	#end

	env.SharedLibrary('../../build/nonlinear_fitter_ceres', sources, LIBS=libs)

#end

env = conf.Finish()

