env = Environment()
env.Append(CPPPATH = ['../../../external/build/include', '../../'])
env.Append(LIBPATH = ['../../../external/build/lib', '../../build'])

sources = ['fitter.cpp']
libs = ['ceres', 'glog', 'gomp', 'core', 'lapack']
env.SharedLibrary('../../build/nonlinear_fitter_ceres', sources, LIBS=libs)
