Import('env')

sources = ['function.cpp']
targets = env.SharedLibrary('#build/plugins/nonlinear_fresnel_normalized_schlick',
                            sources, LIBS = env['PLUGIN_LIB'])
Return('targets')
